name: Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        mono_version: ["6.4.0.198", "6.6.0.161", "6.8.0.123", "6.10.0.105", "6.12.0.93"]

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: |
        echo ${GHCR_KEY} | docker login -u ${GITHUB_ACTOR} --password-stdin ghcr.io
        echo ${DOCKER_HUB_KEY} | docker login -u cmbdevopsbot --password-stdin
      env:
        GHCR_KEY: ${{ secrets.GHCR_KEY }}
        DOCKER_HUB_KEY: ${{ secrets.DOCKER_HUB_KEY }}
    - name: Build Docker image
      run: | 
        docker build . --file Dockerfile --build-arg mono_version=${{ matrix.mono_version }} --tag ghcr.io/combinationab/mono-alpine:${{ matrix.mono_version }}
        docker tag ghcr.io/combinationab/mono-alpine:${{ matrix.mono_version }} combination/mono-alpine:${{ matrix.mono_version }}
    - name: Push Docker image
      run: |
        docker push ghcr.io/combinationab/mono-alpine:${{ matrix.mono_version }}
        docker push combination/mono-alpine:${{ matrix.mono_version }}
